### ISSUE TITLE
opentracing-js vs opentracing-javascript

### ISSUE THREAD

**Issue by slimsag** [opentracing/opentracing-javascript#1]
I think it'd be a bit cleaner to name it `opentracing-js`, no? just a thought

**Comment by bcronin** [comment]
I can see arguments either way. Fortunately, Github repos are easy to rename if there's a strong consensus one way or the other. For what it's worth the NPM package name is just `opentracing` so it's a non-issue on that front.

**Comment by yurishkuro** [comment]
I suggest keeping the full language name, i.e. javascript, rather than abbreviation, however common. E.g. we didn't name the python repo opentracing-py

**Comment by bensigelman** [comment]
For my part:
1. I don't feel strongly
1. I don't feel strongy :)
1. `opentracing-javascript` seems better since someday there are going to be dozens of these things and being pedantic about platform names makes sense in that context. Also, as @bcronin says, javascript programmers will just call the npm package `opentracing` so it's a moot point from that angle.

**Comment by slimsag** [comment]
I hadn't considered the part where the npm package name would be different, that makes more sense. @yurishkuro makes a good point about the python lib too.

Sorry for the noise :) will close now
