### ISSUE TITLE
Opentracing Compatibility tests are inaccurate

### ISSUE THREAD

**Issue by oibe** [opentracing/opentracing-javascript#54]
@bcronin @bensigelman 
1.) In apiCompatibilityChecks the "createTracer" function is never used, so that means I can't import these tests as a client, since my tracer will never be applied.
2.)  The tests assert that errors are thrown when certain conditions are not met, and that certain types are passed in.  My issue with this is that it may be dictating the responsibility of the implementation too much.  For example at Uber a lot of our clients do not throw exceptions, because they would require try/catch which deoptimizes the v8 interpreter, and also there is usually nothing you can do about some of these errors.  (sidenote: There is a larger solution in place so apps, don't crash.)

Essentially I would like to be able to use opentracing compatibility tests without the additional restrictions of typechecking, and error's being thrown.

**Comment by yurishkuro** [comment]
My 2c is that the tests that check for errors to be thrown on invalid arguments do not belong in the API test harness, since those errors are not required by the API. These tests are only testing the specific implementation, which happens to be the default noop tracer. I suggest moving those out to a separate test file.

**Comment by yurishkuro** [comment]
My 2c is that the tests that check for errors to be thrown on invalid arguments do not belong in the API test harness, since those errors are not required by the API. These tests are only testing the specific implementation, which happens to be the default noop tracer. I suggest moving those out to a separate test file.

**Comment by bcronin** [comment]
@oibe, you're right regarding (1). That's a pretty embarrassing oversight :)

Regarding (2), it only throws exceptions in when NODE_ENV="debug" for the very reason that you're describing (more generally, tracing should not interfere with the control flow of the host application, which presumably *should not* be running in NODE_ENV="debug" in production environments). In fact, the code in `lib/` uses babel to drop those checks entirely in the production version (v8 doesn't have to do any optimizations since that code isn't even there). That said, I don't feel strongly about that code  and if you want to remove it, I don't mind.  

All in all, I'm not really using or relying on this API test harness for the LightStep code (which largely explains why I missed that problem that I added `createTracer` be didn't add the necessary calls). As such, since you actually have a specific use case and requirements for the API test harness, do you want to submit a PR to refactor the code to be what you need? That seems like the most direct way of resolving this.
